trigger:
- main

pool:
  name: 'Default'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK 6.0.302'
  inputs:
    packageType: 'sdk'
    version: '6.0.302'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: UiPathPack@5
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\project.json'
    orchestratorConnection: 'AzureDevOps-UiPath'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy@5
  inputs:
    orchestratorConnection: 'AzureDevOps-UiPath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output'
    folderName: 'Autopilot'
    processName: 'ProcessNetworkEnquiries'

